export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_REQUESTED = 'SET_LOADING_REQUESTED';
export const GET_POST = 'GET_POST';
export const GET_POST_REQUESTED = 'GET_POST_REQUESTED';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_REQUESTED = 'DELETE_POST_REQUESTED';
